repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: (doc/ReleaseNotes.md)
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: ./.github/scripts/run_pre_commit.py
        types: [c++]
        language: system
      - id: ruff-format
        name: ruff-format
        entry: ruff format --force-exclude
        types: [python]
        language: system
